// Hand-written fixtures — not generated by exportOtio.
// A fixture produced by the code under test proves nothing about format correctness.

export type Json = Record<string, unknown>;

export const otioTime = (value: number, rate: number): Json => ({
  OTIO_SCHEMA: "RationalTime.1",
  rate,
  value,
});

export const otioRange = (
  start: number,
  duration: number,
  rate: number,
): Json => ({
  OTIO_SCHEMA: "TimeRange.1",
  start_time: otioTime(start, rate),
  duration: otioTime(duration, rate),
});

export const externalReference = (
  targetUrl: string,
  available: Json | null,
): Json => ({
  OTIO_SCHEMA: "ExternalReference.1",
  target_url: targetUrl,
  available_range: available,
  metadata: {},
});

export const missingReference = (): Json => ({
  OTIO_SCHEMA: "MissingReference.1",
  name: "",
  available_range: null,
  metadata: {},
});

/** A media clip: source window + an ExternalReference. */
export const otioClip = (options: {
  name?: string;
  sourceStart: number;
  duration: number;
  rate: number;
  targetUrl: string;
  /** null = the exporting tool never wrote `available_range` . */
  available?: { start: number; duration: number; rate: number } | null;
  schema?: string;
}): Json => ({
  OTIO_SCHEMA: options.schema ?? "Clip.1",
  name: options.name ?? "",
  source_range: otioRange(options.sourceStart, options.duration, options.rate),
  media_reference: externalReference(
    options.targetUrl,
    options.available
      ? otioRange(
          options.available.start,
          options.available.duration,
          options.available.rate,
        )
      : null,
  ),
  effects: [],
  markers: [],
  metadata: {},
});

/** — a FrameBranch text clip travels in `metadata.framebranch`. */
export const otioTextClip = (options: {
  duration: number;
  rate: number;
  textContent: unknown;
  textStyle?: unknown;
}): Json => ({
  OTIO_SCHEMA: "Clip.1",
  name: "",
  source_range: otioRange(0, options.duration, options.rate),
  media_reference: missingReference(),
  effects: [],
  markers: [],
  metadata: {
    framebranch: {
      kind: "text",
      textContent: options.textContent,
      ...(options.textStyle === undefined
        ? {}
        : { textStyle: options.textStyle }),
    },
  },
});

/** Real OTIO gaps are named "Filler". */
export const otioGap = (duration: number, rate: number): Json => ({
  OTIO_SCHEMA: "Gap.1",
  name: "Filler",
  source_range: otioRange(0, duration, rate),
  effects: [],
  markers: [],
  metadata: {},
});

export const otioTransition = (): Json => ({
  OTIO_SCHEMA: "Transition.1",
  name: "cross-dissolve",
  transition_type: "SMPTE_Dissolve",
  in_offset: otioTime(2, 24),
  out_offset: otioTime(2, 24),
  metadata: {},
});

export const otioTrack = (options: {
  kind: "Video" | "Audio";
  children: Json[];
  /** — set for a FrameBranch text track. */
  framebranchText?: boolean;
  schema?: string;
}): Json => ({
  OTIO_SCHEMA: options.schema ?? "Track.1",
  name: "",
  kind: options.kind,
  children: options.children,
  effects: [],
  markers: [],
  metadata: options.framebranchText ? { framebranch: { kind: "text" } } : {},
});

export const otioTimeline = (options: {
  tracks: Json[];
  /** Present → rule (1); its VALUE is always ignored. */
  globalStart?: { value: number; rate: number };
}): Json => ({
  OTIO_SCHEMA: "Timeline.1",
  name: "fixture",
  ...(options.globalStart
    ? {
        global_start_time: otioTime(
          options.globalStart.value,
          options.globalStart.rate,
        ),
      }
    : {}),
  tracks: {
    OTIO_SCHEMA: "Stack.1",
    name: "tracks",
    children: options.tracks,
    effects: [],
    markers: [],
    metadata: {},
  },
  metadata: {},
});

/**
 * 's positive half: ONE fully literal document that uses all nine
 * whitelisted labels — Timeline.1, Stack.1, Track.1, Clip.1, Gap.1,
 * TimeRange.1, RationalTime.1, ExternalReference.1, MissingReference.1.
 */
export const ALL_WHITELIST_LABELS_DOC: Json = {
  OTIO_SCHEMA: "Timeline.1",
  name: "whitelist",
  global_start_time: { OTIO_SCHEMA: "RationalTime.1", rate: 24, value: 0 },
  tracks: {
    OTIO_SCHEMA: "Stack.1",
    name: "tracks",
    children: [
      {
        OTIO_SCHEMA: "Track.1",
        name: "V1",
        kind: "Video",
        children: [
          {
            OTIO_SCHEMA: "Clip.1",
            name: "shot",
            source_range: {
              OTIO_SCHEMA: "TimeRange.1",
              start_time: { OTIO_SCHEMA: "RationalTime.1", rate: 24, value: 5 },
              duration: { OTIO_SCHEMA: "RationalTime.1", rate: 24, value: 10 },
            },
            media_reference: {
              OTIO_SCHEMA: "ExternalReference.1",
              target_url: "file://shot.mov",
              available_range: {
                OTIO_SCHEMA: "TimeRange.1",
                start_time: {
                  OTIO_SCHEMA: "RationalTime.1",
                  rate: 24,
                  value: 0,
                },
                duration: {
                  OTIO_SCHEMA: "RationalTime.1",
                  rate: 24,
                  value: 480,
                },
              },
              metadata: {},
            },
            metadata: {},
          },
          {
            OTIO_SCHEMA: "Gap.1",
            name: "Filler",
            source_range: {
              OTIO_SCHEMA: "TimeRange.1",
              start_time: { OTIO_SCHEMA: "RationalTime.1", rate: 24, value: 0 },
              duration: { OTIO_SCHEMA: "RationalTime.1", rate: 24, value: 4 },
            },
            metadata: {},
          },
        ],
        metadata: {},
      },
      {
        OTIO_SCHEMA: "Track.1",
        name: "T1",
        kind: "Video",
        children: [
          {
            OTIO_SCHEMA: "Clip.1",
            name: "caption",
            source_range: {
              OTIO_SCHEMA: "TimeRange.1",
              start_time: { OTIO_SCHEMA: "RationalTime.1", rate: 24, value: 0 },
              duration: { OTIO_SCHEMA: "RationalTime.1", rate: 24, value: 6 },
            },
            media_reference: {
              OTIO_SCHEMA: "MissingReference.1",
              name: "",
              available_range: null,
              metadata: {},
            },
            metadata: {
              framebranch: {
                kind: "text",
                textContent: "Hello",
                textStyle: { font: "Georgia", size: 32, color: "#00ff00" },
              },
            },
          },
        ],
        metadata: { framebranch: { kind: "text" } },
      },
    ],
    metadata: {},
  },
  metadata: {},
};
