/**
 * clip-helpers.ts — small, framework-free helpers for rendering the
 * engine's `Clip | TextClip` union. Imported by UI AND server code (the diff
 * presenter), so nothing React-specific may live here.
 *
 * Display names (D4(1), copy sheet #125): the engine now carries an
 * optional, non-semantic `name` on Clip / TextClip / Track (read from the
 * OTIO clip/track name). A raw id is NEVER shown to a user: the fallbacks
 * below are the media filename, the text content, and finally
 * `Untitled clip`.
 */

import type {
  Clip,
  MediaRef,
  TextClip,
  Timeline,
  Track,
} from "@framebranch/engine";

export type AnyClip = Clip | TextClip;

export function isTextClip(clip: AnyClip): clip is TextClip {
  return "textContent" in clip;
}

export function findMediaRef(
  timeline: Timeline,
  mediaRefId: string,
): MediaRef | undefined {
  return timeline.mediaRefs.find((ref) => ref.id === mediaRefId);
}

/**
 * M8b — selection is kept as an id (Shell.tsx), never a snapshot object:
 * every edit replaces the timeline in the query cache, and a stored object
 * reference would go stale the instant its own value changed (e.g. a
 * volume slider would keep showing the pre-drag number). This is the one
 * read site that turns an id back into the live clip.
 */
export function findClipById(
  timeline: Timeline,
  clipId: string,
): AnyClip | undefined {
  for (const track of timeline.tracks) {
    const clip = (track.clips as AnyClip[]).find((c) => c.id === clipId);
    if (clip) return clip;
  }
  return undefined;
}

/** `/media/interview.mp4` → `interview` */
export function fileStem(url: string): string {
  const base = url.split("/").pop() ?? url;
  return base.replace(/\.[^./]+$/, "");
}

/** `/media/interview.mp4` → `Interview`; `/media/b_roll.mp4` → `B Roll`. */
export function labelFromMediaUrl(url: string): string {
  const stem = fileStem(url);
  const words = stem.replace(/[-_]+/g, " ").trim();
  if (words.length === 0) return stem;
  return words.replace(/\b\w/g, (c) => c.toUpperCase());
}

/** Text clips fall back to their content, cut at 24 characters. */
export const TEXT_NAME_MAX = 24;

/** Copy sheet #125 — the last-resort name. Never a raw id. */
export const UNTITLED_CLIP = "Untitled clip";
export const EMPTY_TEXT = "Empty text";

/**
 * D4(1) — the one place a clip gets its human name.
 *   1. `clip.name` (the OTIO clip name, trimmed)
 *   2. media clip → the media filename without extension, title-cased
 *   3. text clip → its text (first 24 chars, `…` if cut); empty → `Empty text`
 *   4. `Untitled clip`
 */
export function clipDisplayName(
  clip: AnyClip,
  mediaRef: MediaRef | undefined,
): string {
  const own = clip.name?.trim();
  if (own) return own;
  if (isTextClip(clip)) {
    const text = clip.textContent.trim();
    if (text.length === 0) return EMPTY_TEXT;
    return text.length > TEXT_NAME_MAX
      ? `${text.slice(0, TEXT_NAME_MAX).trimEnd()}…`
      : text;
  }
  if (mediaRef) return labelFromMediaUrl(mediaRef.url);
  return UNTITLED_CLIP;
}

/**
 * Track display: `track.name` → else `V1/V2…` (video), `A1/A2…` (audio),
 * `T1/T2…` (text), numbered by position among tracks of the same kind.
 */
export function trackDisplayName(track: Track, timeline: Timeline): string {
  const own = track.name?.trim();
  if (own) return own;
  const sameKind = timeline.tracks.filter((t) => t.kind === track.kind);
  const index = sameKind.findIndex((t) => t.id === track.id);
  const prefix = track.kind === "video" ? "V" : track.kind === "audio" ? "A" : "T";
  return `${prefix}${(index === -1 ? sameKind.length : index) + 1}`;
}

/**
 * M8 lock 6 — thumbnails are pre-made images, one `.jpg` per media
 * fixture, sharing the media's own filename stem
 * (apps/web/public/thumbnails/<stem>.jpg — thumbnails are pre-generated).
 */
export function thumbnailUrl(mediaUrl: string): string {
  return `/thumbnails/${fileStem(mediaUrl)}.jpg`;
}

/** One-second source frames generated from the actual media file. */
export function filmstripFrameUrl(mediaUrl: string, second: number): string {
  return `/thumbnails/frames/${fileStem(mediaUrl)}-${String(second + 1).padStart(2, "0")}.jpg`;
}

/** Full-source waveform generated by decoding the audio file. */
export function waveformUrl(mediaUrl: string): string {
  return `/thumbnails/${fileStem(mediaUrl)}-waveform.png`;
}
